# Generated by Django 3.0.7 on 2020-06-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_timestamp', models.CharField(blank=True, default='', max_length=100)),
                ('environmental_dimension', models.CharField(choices=[('light', 'light'), ('soil_moisture', 'soil_moisture'), ('air_temperature', 'air_temperature')], max_length=100)),
                ('environmental_value', models.IntegerField()),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.Plant')),
            ],
            options={
                'verbose_name': 'Plant measurment',
                'verbose_name_plural': 'Plant measurments',
                'db_table': 'plant_measurements',
                'ordering': ['measurement_timestamp'],
                'get_latest_by': "measurement_timestamp'",
                'unique_together': {('id', 'measurement_timestamp')},
            },
        ),
    ]
