# Generated by Django 3.0.7 on 2020-06-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0002_plantmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmeasurement',
            name='measurement_timestamp',
            field=models.DateTimeField(),
        ),
    ]
