# Generated by Django 3.0.7 on 2020-06-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0003_auto_20200626_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantmeasurement',
            old_name='d',
            new_name='plant_id',
        ),
        migrations.AlterUniqueTogether(
            name='plantmeasurement',
            unique_together=set(),
        ),
    ]
