# Generated by Django 3.0.7 on 2020-06-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0005_auto_20200627_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted_date',
            field=models.DateField(blank=True),
        ),
    ]
