# Generated by Django 3.0.7 on 2020-06-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0006_auto_20200627_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
