# Generated by Django 3.0.7 on 2020-06-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0008_auto_20200627_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='plant',
            name='owner',
        ),
    ]
