# Generated by Django 3.0.7 on 2020-07-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0009_auto_20200627_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoBoard',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(choices=[('Mega', 'Mega')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('environmental_dimension', models.CharField(choices=[('light', 'light'), ('soil_moisture', 'soil_moisture'), ('air_temperature', 'air_temperature')], max_length=100)),
                ('arduino_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garden_app.ArduinoBoard')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='arduino_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garden_app.ArduinoBoard'),
        ),
    ]
