# Generated by Django 3.0.7 on 2020-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0011_auto_20200706_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinopin',
            name='environmental_dimension',
            field=models.CharField(choices=[('light', 'light'), ('soil_moisture', 'soil_moisture'), ('air_temperature', 'air_temperature')], default='light', max_length=100),
            preserve_default=False,
        ),
    ]
