# Generated by Django 3.0.7 on 2020-07-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0013_arduinopin_is_collecting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arduinopin',
            unique_together={('arduino_id', 'pin_number')},
        ),
        migrations.RemoveField(
            model_name='arduinopin',
            name='plant_id',
        ),
    ]
