# Generated by Django 3.0.7 on 2020-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0014_auto_20200706_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinoboard',
            name='model_name',
            field=models.CharField(choices=[('UNO', 'Uno'), ('MEGA', 'Mega')], max_length=100),
        ),
        migrations.AlterField(
            model_name='arduinopin',
            name='pin_number',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15')], max_length=5),
        ),
    ]
