# Generated by Django 3.0.7 on 2020-07-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0015_auto_20200707_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='arduino_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='garden_app.ArduinoBoard'),
        ),
    ]
