# Generated by Django 3.0.7 on 2020-07-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0016_auto_20200707_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinopin',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garden_app.Plant'),
        ),
    ]
