# Generated by Django 3.0.7 on 2020-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0017_arduinopin_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinopin',
            name='pin_number',
            field=models.CharField(choices=[('a:0:i', 'A:0:I'), ('a:1:i', 'A:1:I'), ('a:2:i', 'A:2:I'), ('a:3:i', 'A:3:I'), ('a:4:i', 'A:4:I'), ('a:5:i', 'A:5:I'), ('a:6:i', 'A:6:I'), ('a:7:i', 'A:7:I'), ('a:8:i', 'A:8:I'), ('a:9:i', 'A:9:I'), ('a:10:i', 'A:10:I'), ('a:11:i', 'A:11:I'), ('a:12:i', 'A:12:I'), ('a:13:i', 'A:13:I'), ('a:14:i', 'A:14:I'), ('a:15:i', 'A:15:I')], max_length=10),
        ),
    ]
