# Generated by Django 3.0.7 on 2020-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0018_auto_20200719_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinopin',
            name='sensor_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arduinopin',
            name='sensor_low',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
